### ISSUE TITLE
we need responsive image

### ISSUE THREAD

**Issue by kevinmora94** [kevinmora94/noviolencia#1]
we have two image as parallax background, we need to make those image responsive
First image: the one in the begin with the caption: "No a la violencia"
Second Image: the image with caption: "No a la violencia, viva la paz"

Some easy issues for hacktoberfest beginners

**Comment by justjackb** [comment]
responsive as in resizing with the background?

**Comment by garg-ravi24** [comment]
made a pull request #2

**Comment by kevinmora94** [comment]
great
